name: theme_json_converter
description: Package that implements JsonConverters from `json_serializable` to material theme classes
version: 0.1.0
repository: https://github.com/massa-org/theme_json_converter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: